import { AssetType } from '../entities/investment.entity';

export interface InvestmentSeedItem {
  assetType: AssetType;
  symbol: string;
  name: string;
  price: number;
}

export const investmentSeedData: InvestmentSeedItem[] = [
  {
    assetType: AssetType.STOCK,
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 213.47,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 482.19,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'GOOGL',
    name: 'Alphabet Inc. Class A',
    price: 191.62,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    price: 226.35,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'META',
    name: 'Meta Platforms, Inc.',
    price: 543.88,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 1362.54,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    price: 247.93,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'BRK.B',
    name: 'Berkshire Hathaway Inc. Class B',
    price: 462.14,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    price: 239.76,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'V',
    name: 'Visa Inc. Class A',
    price: 314.27,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'MA',
    name: 'Mastercard Incorporated Class A',
    price: 521.44,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'WMT',
    name: 'Walmart Inc.',
    price: 82.11,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'PG',
    name: 'The Procter & Gamble Company',
    price: 177.93,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    price: 71.58,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'PEP',
    name: 'PepsiCo, Inc.',
    price: 184.06,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    price: 126.49,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'CVX',
    name: 'Chevron Corporation',
    price: 169.72,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'UNH',
    name: 'UnitedHealth Group Incorporated',
    price: 531.08,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    price: 164.37,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'PFE',
    name: 'Pfizer Inc.',
    price: 33.84,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'HD',
    name: 'The Home Depot, Inc.',
    price: 386.92,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'COST',
    name: 'Costco Wholesale Corporation',
    price: 932.16,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'MCD',
    name: 'McDonald\'s Corporation',
    price: 301.55,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'NKE',
    name: 'NIKE, Inc. Class B',
    price: 104.29,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    price: 112.74,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'NFLX',
    name: 'Netflix, Inc.',
    price: 757.61,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    price: 588.33,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'CRM',
    name: 'Salesforce, Inc.',
    price: 293.85,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    price: 173.66,
  },
  {
    assetType: AssetType.STOCK,
    symbol: 'INTC',
    name: 'Intel Corporation',
    price: 39.47,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    price: 751.71,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    price: 690.92,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    price: 755.07,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    price: 724.23,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    price: 342.15,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'IEFA',
    name: 'iShares Core MSCI EAFE ETF',
    price: 82.4,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'VEA',
    name: 'Vanguard FTSE Developed Markets ETF',
    price: 54.65,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'VTV',
    name: 'Vanguard Value ETF',
    price: 178.9,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'VUG',
    name: 'Vanguard Growth ETF',
    price: 422.3,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    price: 248.5,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'IEMG',
    name: 'iShares Core MSCI Emerging Markets ETF',
    price: 58.15,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'SCHD',
    name: 'Schwab U.S. Dividend ETF',
    price: 92.45,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    price: 220.12,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    price: 49.6,
  },
  {
    assetType: AssetType.ETF,
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    price: 265.8,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'AGG',
    name: 'iShares Core U.S. Aggregate Bond ETF',
    price: 96.84,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'BND',
    name: 'Vanguard Total Bond Market ETF',
    price: 72.15,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    price: 89.4,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'IEF',
    name: 'iShares 7-10 Year Treasury Bond ETF',
    price: 93.1,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'SHY',
    name: 'iShares 1-3 Year Treasury Bond ETF',
    price: 82.95,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'BNDX',
    name: 'Vanguard Total International Bond ETF',
    price: 49.2,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'LQD',
    name: 'iShares iBoxx $ Investment Grade Corporate Bond ETF',
    price: 108.65,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    price: 79.1,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'EMB',
    name: 'iShares J.P. Morgan USD Emerging Markets Bond ETF',
    price: 86.35,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'VCSH',
    name: 'Vanguard Short-Term Corporate Bond ETF',
    price: 78.4,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'VCIT',
    name: 'Vanguard Intermediate-Term Corporate Bond ETF',
    price: 81.15,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'SCHZ',
    name: 'Schwab U.S. Aggregate Bond ETF',
    price: 48.25,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'JNK',
    name: 'SPDR Bloomberg High Yield Bond ETF',
    price: 94.8,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'TIP',
    name: 'iShares TIPS Bond ETF',
    price: 106.5,
  },
  {
    assetType: AssetType.BOND,
    symbol: 'VGSH',
    name: 'Vanguard Short-Term Treasury ETF',
    price: 58.9,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VFIAX',
    name: 'Vanguard 500 Index Fund Admiral Shares',
    price: 690.52,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VTSAX',
    name: 'Vanguard Total Stock Market Index Fund Admiral Shares',
    price: 180.87,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'FXAIX',
    name: 'Fidelity 500 Index Fund',
    price: 210.45,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VTIAX',
    name: 'Vanguard Total International Stock Index Fund Admiral Shares',
    price: 34.6,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VBTLX',
    name: 'Vanguard Total Bond Market Index Fund Admiral Shares',
    price: 9.85,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'FSKAX',
    name: 'Fidelity Total Market Index Fund',
    price: 165.2,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VIGAX',
    name: 'Vanguard Growth Index Fund Admiral Shares',
    price: 215.4,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'FFFQX',
    name: 'Fidelity Freedom Index 2050 Fund Investor Class',
    price: 23.95,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'TRBCX',
    name: 'T. Rowe Price Blue Chip Growth Fund',
    price: 194.1,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VWELX',
    name: 'Vanguard Wellington Fund Investor Shares',
    price: 48.65,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'FCNTX',
    name: 'Fidelity Contrafund',
    price: 22.35,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VMFXX',
    name: 'Vanguard Federal Money Market Fund',
    price: 1,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'SWPPX',
    name: 'Schwab S&P 500 Index Fund',
    price: 98.4,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'VVIAX',
    name: 'Vanguard Value Index Fund Admiral Shares',
    price: 64.8,
  },
  {
    assetType: AssetType.MUTUAL_FUND,
    symbol: 'FDIVX',
    name: 'Fidelity Diversified International Fund',
    price: 46.15,
  },
  {
    assetType: AssetType.ETF,
    symbol: '0820EA',
    name: 'FTSE4Good ETF',
    price: 0.91,
  },
  {
    assetType: AssetType.ETF,
    symbol: '0829EA',
    name: 'TradePlus S&P New China Tracker (MYR)',
    price: 5.23,
  },
  {
    assetType: AssetType.ETF,
    symbol: '0822EA',
    name: 'Principal FTSE ASEAN 40 ETF',
    price: 1.74,
  },
  {
    assetType: AssetType.ETF,
    symbol: '0828EA',
    name: 'TradePlus Shariah Gold Tracker',
    price: 3.45,
  },
  {
    assetType: AssetType.ETF,
    symbol: '0834EA',
    name: 'Kenanga KLCI Daily 2X Leveraged ETF',
    price: 2.1,
  },
];