### Health Check
GET http://localhost:3000/health

###

### API Root
GET http://localhost:3000/api/v1

###

### Login
# @name login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123"
}

###

@token={{login.response.body.accessToken}}

### Profile
GET http://localhost:3000/api/auth/profile
Authorization: Bearer {{token}}